name: myxcreate
description: A new Flutter project.
publish_to: 'none'

version: 1.0.6+3

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.2.2
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  video_player: ^2.10.0
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  app_links: ^6.4.1
  share_plus: ^11.1.0
  flutter_foreground_task: ^9.1.0
  notification_listener_service: ^0.3.4
  installed_apps: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/x.png"

flutter_native_splash:
  color: "#ffffff"        # Warna background splash
  image: assets/splash.png      # Path ke gambar
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: scaleAspectFill


flutter:
  uses-material-design: true

  assets:
    - assets/x.png
    - assets/splash.png
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
