# Buat folder jika belum ada
- name: Prepare artifact folder
  run: mkdir -p build/app/outputs/flutter-apk/

# Upload semua APK
- name: Upload APK artifact
  uses: actions/upload-artifact@v4
  with:
    name: release-apk
    path: build/app/outputs/flutter-apk/*.apk
