name: Build & Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java (untuk Gradle)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Setup Flutter versi 3.32.8
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK release
      - name: Build release APK
        run: flutter build apk --release

      # Cari file APK hasil build
      - name: Find APK file
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*.apk" | grep "app-release.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "APK file not found!"
            exit 1
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Found APK at $APK_PATH"
      
      # Create a new GitHub Release (otomatis)
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}  # otomatis tag versi unik
          name: Release v${{ github.run_number }}
          body: "Automated Flutter APK release #${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload APK ke Release yang baru dibuat
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APK_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
