name: Build & Publish Release APK

# Workflow jalan saat push ke main atau saat bikin Release
on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java (untuk Gradle)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Setup Flutter terbaru (>=3.13 untuk Dart 3.6+)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0" # sesuaikan versi Flutter terbaru

      # Pastikan dependencies terinstal
      - name: Install dependencies
        run: flutter pub get

      # Build APK release
      - name: Build release APK
        run: flutter build apk --release

      # Upload APK sebagai artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
